//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.16 at 04:13:05 PM CET 
//

@ae.javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/ns/sawsdl")
package org.ow2.easywsdl.extensions.sawsdl.org.w3.ns.sawsdl;
